spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      file: ../compose.yaml
      lifecycle-management: start-only
